[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#696969"
blue = "#79d2ff"
cyan = "#87a8af"
green = "#a6e179"
magenta = "#bb5d79"
red = "#ed4c7a"
white = "#e2f1f6"
yellow = "#ffdf6b"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#151515"
blue = "#a6e2f0"
cyan = "#5f868f"
green = "#a6e25f"
magenta = "#e85b92"
red = "#ff8eaf"
white = "#d5f1f2"
yellow = "#f8e578"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/bash"

[window]
decorations = "buttonless"
opacity = 0.8


[[hints.enabled]]
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

